DROP TABLE IF EXISTS projects;

DROP TYPE IF EXISTS CURRENT_STATUS;
CREATE TYPE CURRENT_STATUS AS ENUM ('in-progress', 'completed');

CREATE TABLE projects (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
    created_at TIMESTAMP DEFAULT now() NOT NULL,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    status CURRENT_STATUS DEFAULT 'in-progress' NOT NULL,
    collaborators TEXT[] DEFAULT ARRAY[]::TEXT[] NOT NULL
);
